Unix Coreutils
codescalersinternships/Coreutils-Rawan-Mostafa pull request #1
Opened 2024-09-02 08:41 UTC by RawanMostafa08

2024-09-08 09:40 UTC, Eslam-Nawara requested changes

2024-09-08 09:40 UTC, Eslam-Nawara commented on .github/workflows/lint_format.yaml
> +    branches: [ "main" ]
run the build, lint and format on push/pr against all branches

2024-09-08 09:40 UTC, Eslam-Nawara commented on .github/workflows/lint_format.yaml
> +    if: github.event_name == 'pull_request'
why doing this?

2024-09-08 09:40 UTC, Eslam-Nawara commented on .github/workflows/lint_format.yaml
> +    timeout-minutes: 5
no need for this

2024-09-08 09:40 UTC, Eslam-Nawara commented on .github/workflows/lint_format.yaml
> +        run: gofmt -s -w . && git diff --exit-code
check this https://github.com/Jerome1337/gofmt-action

2024-09-08 09:40 UTC, Eslam-Nawara commented on cmd/cat/main.go
> +	}
for simplicity we can do something like this

```suggestion
	scanner := bufio.NewScanner(os.Stdin)
	if len(flag.Args()) > 0 && flag.Args()[0] != "-" {
		data, err := os.ReadFile(flag.Args()[0])
		if err != nil {
			log.Fatal("Error in reading the file")
		}
		scanner = bufio.NewScanner(strings.NewReader(string(data)))
	}
```

2024-09-08 09:40 UTC, Eslam-Nawara commented on internal/cat.go
> +		}
return the error to the caller function and let the user decide what to do with the error, and log it from the main

2024-09-08 09:40 UTC, Eslam-Nawara commented on internal/yes.go
> +	input := strings.Join(inputs, " ")
if no arguments were passed, the default behavior is to print y infinitely

2024-09-08 09:40 UTC, Eslam-Nawara commented on internal/echo.go
> +		fmt.Printf("%s ", arg)
you can do `strings.Join(args, " ")` this will return one string containing all the args separated by space

2024-09-08 09:40 UTC, Eslam-Nawara commented on cmd/head/main.go
> +	scanner := bufio.NewScanner(strings.NewReader(string(data)))
why not open the file and use the returned reader to scan the file?

2024-09-08 09:40 UTC, Eslam-Nawara commented on cmd/head/main.go
> +	scanner := bufio.NewScanner(strings.NewReader(string(data)))
same for all

2024-09-08 10:50 UTC, RawanMostafa08 commented on .github/workflows/lint_format.yaml
> +        run: gofmt -s -w . && git diff --exit-code
@Eslam-Nawara tab what's wrong with the existing?

2024-09-08 11:29 UTC, Eslam-Nawara commented on .github/workflows/lint_format.yaml
> +        run: gofmt -s -w . && git diff --exit-code
I don't think it would matter, just easier/less error prone using `uses: Jerome1337/gofmt-action` instead of typing the command

2024-09-08 11:56 UTC, RawanMostafa08 commented on cmd/head/main.go
> +	scanner := bufio.NewScanner(strings.NewReader(string(data)))
Isn't it the same tayeb? changing the file reading logic for all utils is too much work now :sob:

2024-09-09 07:53 UTC, AbdelrahmanElawady requested changes
Nice work Rawan! Some minor comments

2024-09-09 07:53 UTC, AbdelrahmanElawady commented on README.md
true, false, yes and env are missing

2024-09-09 07:53 UTC, AbdelrahmanElawady commented on cmd/head/main.go
> +	scanner := bufio.NewScanner(strings.NewReader(string(data)))
loading the whole file and printing 5 lines is very inefficient. Say, you have 4GB file and you want to read 5 lines, now you have 4GB in memory just to read less than a Kilobyte.

2024-09-09 07:53 UTC, AbdelrahmanElawady commented on cmd/tree/main.go
> +	}
```suggestion
	dir, err := os.Getwd()
	if err != nil {
		log.Fatal("Error reaching the current directory")
	}
	if len(flag.Args()) != 0 {
		dir = flag.Args()[0]
	}
	internal.Tree(dir, 0, maxDepth)
```

less indentation and easier to read

2024-09-09 07:53 UTC, AbdelrahmanElawady commented on internal/tail.go
> +	count := 0
count is not used right? if yes please remove it

2024-09-09 07:53 UTC, AbdelrahmanElawady commented on internal/tree.go
> +	formattedPrint(pathParts[len(pathParts)-1], depth)
you can use `filepath.Base(directoryPath)` to get the last element in the path

2024-09-09 07:53 UTC, AbdelrahmanElawady commented on internal/wc.go
> +	fmt.Print("\n")
file name should be printed, similar to wc

2024-09-09 07:53 UTC, AbdelrahmanElawady commented on internal/yes.go
> +	}
```suggestion
	output := "y"
	if len(inputs) > 0 {
		output = strings.Join(inputs, " ")
	}
	for {
		fmt.Println(output)
	}
```

2025-01-13 09:00 UTC, xmonader approved these changes

2025-01-13 09:00 UTC, xmonader approved these changes

2025-01-13 09:19 UTC, merged